[config]
schemaVersion = "0.0.1"

[package]
namespace = "Gogas1"
name = "ExtendedStoryModeSettings"
versionNumber = "0.1.1"
description = "Extends the story mode settings with the ability to weaken Yi"
websiteUrl = "https://github.com/Gogas1/ExtendedStoryModeSettings"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"
"ninesolsmodding-NineSolsAPI" = "1.3.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
